; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Rainfall Credit:
; FAMISTUDIO_USE_VOLUME_TRACK = 1

.export _music_data_rainfall_credit:=music_data_rainfall_credit

music_data_rainfall_credit:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Credit
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 2, 0

.export music_data_rainfall_credit
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env2,@env3,@env0 ; 00 : Acoustic Grand Piano

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$7f,$00,$02
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00

@samples:

@tempo_env_1_mid:
	.byte $03,$06,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $80, $2e, $99, $33, $8b, $2e, $8b, $36, $99, $33, $99, $00
	.byte $99, $2e, $99, $36, $b5, $2f, $99, $33, $8b, $2f, $8b, $36, $99, $33, $99, $38, $99, $36, $99, $33, $b5, $48, $77, $2e
	.byte $99, $78, $31, $8b, $77, $2e, $8b, $78, $36, $99, $77, $31, $99, $00, $99, $2e, $99, $78, $31, $b5, $77, $2e, $99, $78
	.byte $31, $8b, $77, $2f, $8b, $2e, $b5, $76, $2c, $b5, $29, $b5, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $80
@song0ref82:
	.byte $01, $00, $97, $01, $00, $89, $01, $00, $c1, $01, $00, $89, $01, $00, $89, $01, $00, $cf
	.byte $41, $12
	.word @song0ref82
	.byte $41, $12
	.word @song0ref82
	.byte $41, $12
	.word @song0ref82
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80, $0f, $ff, $d9, $00, $81, $0b, $ff, $d7, $00, $83, $12, $ff, $dd, $0a, $ff, $dd, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $80
@song0ref135:
	.byte $19, $00, $b3, $19, $00, $b3, $19, $00, $b3, $19, $00, $b3
	.byte $41, $0c
	.word @song0ref135
	.byte $41, $0c
	.word @song0ref135
	.byte $41, $0c
	.word @song0ref135
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $ff, $ff, $ff, $bf, $ff, $ff, $ff, $bf, $42
	.word @song0ch4loop
